#
# use http://lint.travis-ci.org/ to validate this file!
#
language: python
python:
  - "3.4"
branches:
  only:
    - master
    - flask
    - develop
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y libjpeg-dev
  - sudo apt-get install -y zlib1g-dev
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source pagapp -m unittest discover
after_success: coveralls

# TODO: do not forget add deployment to the PyPI: http://docs.travis-ci.com/user/deployment/pypi/
# TODO: do not forget add uploading GitHum Releases: http://docs.travis-ci.com/user/deployment/releases/
