# use http://lint.travis-ci.org/ to validate this file!
#
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source pagapp -m unittest discover
after_success: coveralls