#
# use http://lint.travis-ci.org/ to validate this file!
#

language: python
sudo: false
python:
  - "3.4"
branches:
  only:
    - master
    - develop
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source pagapp -m unittest discover
after_success: coveralls
deploy:
  provider: pypi
  user: h0rr0rrdrag0n
  password:
    secure: BoeUW6Kp6U0mxOkim8qSDWMoeq+n5ipAjLLr16O5cnTsS+f4ucttizGd4ayHKCFa6c2Yk164WY4cOdxK3L0pd/MHWGgWErlYpuh/eQRC8zQXYztgkXQXSh+xf2OHlAife1M5R6WYwtpuuYn482rgMsYHWJUGAihXO2gvIb8B4Rc=
  on:
    branch: master
addons:
  apt:
    packages:
      - python3-dev
      - libjpeg-dev
      - zlib1g-dev
